export const SHOP_LOGIN_REQUEST = "SHOP_LOGIN_REQUEST";
export const SHOP_LOGIN_SUCCESS = "SHOP_LOGIN_SUCCESS";
export const SHOP_LOGIN_FAIL = "SHOP_LOGIN_FAIL";

export const LOAD_SHOP_REQUEST = "LOAD_SHOP_REQUEST";
export const LOAD_SHOP_SUCCESS = "LOAD_SHOP_SUCCESS";
export const LOAD_SHOP_FAIL = "LOAD_SHOP_FAIL";

export const SHOP_LOGOUT_SUCCESS = "SHOP_LOGOUT_SUCCESS";
export const SHOP_LOGOUT_FAIL = "SHOP_LOGOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
